import type { Metadata } from "next";
import { Calendar } from "lucide-react";
import { LeadCaptureForm } from "@/features/leads/ui/LeadCaptureForm";
import { Container, Heading, Eyebrow } from "@/components/ui";
import { Card } from "@/components/ui/Surfaces";
import { NextStepCTA } from "@/components/ui/NextStepCTA";

export const metadata: Metadata = { title: "Jonli meetlar va yozuvlar", description: "Naqsh jonli sessiyalari va ochiq AI yozuvlari." };
const meets = [{ title: "Claude Code bilan Telegram bot yaratish", date: "18-Oktyabr, 2026 · 20:00", live: true, text: "Jonli sessiyada bot loyihasini bosqichma-bosqich quramiz." }, { title: "Cursor IDE va VS Code: AI agentlarni sozlash", date: "28-Avgust, 2026", live: false, text: "Koddagi xatolarni tezroq topish bo‘yicha amaliy meet yozuvi." }];
export default function Page() { return <div className="bg-bg text-ink"><Container className="py-20 sm:py-28"><Eyebrow>Jonli sessiyalar</Eyebrow><Heading as="h1" className="mt-3">Meetlar va yozuvlar</Heading><p className="mt-4 max-w-2xl text-lg text-ink-muted">Savollarga javob olish va birga kodlash uchun ochiq sessiyalar.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{meets.map(meet => <Card key={meet.title} className="flex flex-col"><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 font-mono text-xs text-accent"><Calendar className="size-4" aria-hidden="true" />{meet.date}</span><span className="rounded-full border border-border px-3 py-1 text-xs">{meet.live ? "Yaqinlashayotgan" : "Yozuv"}</span></div><Heading as="h2" className="mt-6 text-2xl">{meet.title}</Heading><p className="mt-3 flex-1 text-sm leading-relaxed text-ink-muted">{meet.text}</p><div className="mt-6"><span className="text-sm text-ink-subtle">Telegram havolasini olish uchun pastdagi shaklni to‘ldiring.</span></div></Card>)}</div><Card className="mt-12 max-w-xl"><LeadCaptureForm source="meetlar" ctaLabel="Meetlarga qo‘shilish" title="Meet havolasini olish" description="Ma’lumotlarni qoldirgandan keyin Telegram havolasi ochiladi." revealUrl="https://t.me/m/ODAfK_QIMjky" revealText="Meet yozuvlari Telegram orqali ochiladi." /></Card></Container><NextStepCTA title="Meetdan keyin o‘z yo‘nalishingizni aniqlang" /></div>; }
