import type { TestimonialItem } from "@/lib/validations/testimonials";
export type { TestimonialItem };

export const STATIC_TESTIMONIALS: TestimonialItem[] = [
  {
    id: "test-01",
    fullName: "Azizbek Rahimov",
    role: "Startap Asoschisi & Boshqaruvchi",
    company: "FastCargo Logistics",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
    courseTitle: "Vibe Coding Express",
    cohortName: "Avgust 2026 Kohortasi",
    type: "video",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "03:45",
    thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    body: "Dasturchilarga sarflanadigan 3 oylik vaqt va 45 million so'mni tejab qoldim. Claude Code va Cursor yordamida o'z logistika kompaniyamiz uchun yuk kuzatish tizimini atigi 8 kunda noldan ishga tushirdik. Bugun platformamizdan 200 dan ortiq haydovchilar foydalanmoqda!",
    rating: 5,
    verified: true,
    resultMetric: "8 kunda to'liq MVP ishga tushdi",
    publishedAt: "2026-08-25",
  },
  {
    id: "test-02",
    fullName: "Nilufar Saidova",
    role: "Product Designer & Tadbirkor",
    company: "EdTech Studio",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80",
    courseTitle: "Vibe Coding Express",
    cohortName: "Sentyabr 2026 Kohortasi",
    type: "video",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "04:12",
    thumbnailUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80",
    body: "Men ilgari faqat Figma'da dizayn chizardim. Lekin Vibecoding Express orqali o'zim o'ylagan dizaynni Next.js va Tailwind'da to'liq jonli saytga aylantirishni o'rgandim. Birinchi mijozim uchun ta'lim platformasini 1200$ ga muvaffaqiyatli topshirdim!",
    rating: 5,
    verified: true,
    resultMetric: "1200$ lik birinchi tijoriy buyurtma",
    publishedAt: "2026-09-02",
  },
  {
    id: "test-03",
    fullName: "Sardor Yusupov",
    role: "Marketing Direktori",
    company: "Apex Media Agency",
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80",
    courseTitle: "AI Asoslari",
    cohortName: "Iyul 2026 Kohortasi",
    type: "text",
    body: "Kompaniyamizda haftasiga 30+ soat vaqt oladigan reklama matnlari, tahlillar va hisobotlarni ChatGPT va Claude agentlariga topshirdik. AI Asoslari kursi jamoamiz unumdorligini 4 barobar oshirdi.",
    rating: 5,
    verified: true,
    resultMetric: "Haftasiga 30+ soat vaqt tejaldi",
    publishedAt: "2026-08-10",
  },
  {
    id: "test-04",
    fullName: "Daler Ikromov",
    role: "Boshlang'ich Dasturchi",
    company: "Fintech Startap",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    courseTitle: "Vibe Coding Express",
    cohortName: "Avgust 2026 Kohortasi",
    type: "text",
    body: "Kursgacha faqat HTML va CSS bilardim. 8 haftalik mentorlik davomida PostgreSQL, Drizzle ORM, Payme to'lovlari va xavfsiz JWT sessiyalarni o'rganib chiqdim. Mentorlar har bir uy vazifamni chuqur tahlil qilib berishgani juda foydali bo'ldi.",
    rating: 5,
    verified: true,
    resultMetric: "Junior'dan Mid-level AI Integratorga",
    publishedAt: "2026-08-28",
  },
  {
    id: "test-05",
    fullName: "Malika Tursunova",
    role: "Onlayn Maktab Asoschisi",
    company: "SmartKids Academy",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    courseTitle: "Vibe Coding Express",
    cohortName: "Iyul 2026 Kohortasi",
    type: "video",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoDuration: "02:50",
    thumbnailUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80",
    body: "Bizga bolalar uchun interaktiv testlar va ota-onalar uchun to'lov qabul qiluvchi shaxsiy tizim kerak edi. Vibe coding tufayli barcha logikani o'zim qurdim. Kurs puli dastlabki 1 haftada o'zini oqladi!",
    rating: 5,
    verified: true,
    resultMetric: "Kurs xarajati 1 haftada qoplandi",
    publishedAt: "2026-07-30",
  },
  {
    id: "test-06",
    fullName: "Bobur Mirzayev",
    role: "Frilanser & No-code Mutaxassisi",
    company: "Upwork Top Rated",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    courseTitle: "Vibe Coding Express",
    cohortName: "Sentyabr 2026 Kohortasi",
    type: "text",
    body: "Oldin Upwork'da faqat kichik veb-saytlar qilardim. Vibe Coding'dan keyin SaaS platformalar va AI integratsiyalarni mustaqil topshira boshladim. Oylik buyurtmalarim qiymati 2 barobar oshdi.",
    rating: 4,
    verified: true,
    resultMetric: "Daromad 2 barobar oshdi",
    publishedAt: "2026-09-04",
  },
  {
    id: "test-07",
    fullName: "Farhod Karimov",
    role: "Restoranlar Tarmog'i Boshqaruvchisi",
    company: "Chustiy Osh Tarmog'i",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
    courseTitle: "AI Asoslari",
    cohortName: "Avgust 2026 Kohortasi",
    type: "text",
    body: "Mijozlar buyurtmalarini avtomatlashtiruvchi Telegram bot va oshxona buyurtmalarini boshqarish panelini o'zimiz yaratdik. Kursdagi materiallar juda amaliy va sodda tilda tushuntirilgan.",
    rating: 5,
    verified: true,
    resultMetric: "Ichki tizim 100% avtomatlashtirildi",
    publishedAt: "2026-08-18",
  },
  {
    id: "test-08",
    fullName: "Shahzod Normatov",
    role: "Buxgalteriya va Audit Maslahatchisi",
    company: "TaxConsult Group",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80",
    courseTitle: "AI Asoslari",
    cohortName: "Iyul 2026 Kohortasi",
    type: "text",
    body: "Katta hajmdagi Excel jadvallari va soliq hisobotlarini AI yordamida daqiqalarda tahlil qilishni o'rgandim. Hisobotlardagi xatoliklar nolga tushdi.",
    rating: 5,
    verified: true,
    resultMetric: "Hisobot xatoliklari 0% ga tushdi",
    publishedAt: "2026-08-05",
  },
];
