import { Clock, DollarSign, PieChart, Users } from "lucide-react";
import type { AnalyticsData } from "@/features/crm/types";
export function formatMoney(value?: number) { return value === undefined || value === null ? "0 so'm" : new Intl.NumberFormat("uz-UZ").format(value) + " so'm"; }
export function StatCards({ summary }: { summary: AnalyticsData["summary"] }) { return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
  <div className="bg-cream border border-border rounded-xl p-5 shadow-sm space-y-2"><div className="flex items-center justify-between text-xs text-ink-muted"><span>Jami Leadlar</span><Users className="w-4 h-4 text-accent" /></div><div className="text-2xl font-bold text-ink">{summary.totalLeads} ta</div><div className="text-xs text-emerald-600 dark:text-emerald-400 font-medium">To'langan: {summary.paidCount} ta lead</div></div>
  <div className="bg-cream border border-border rounded-xl p-5 shadow-sm space-y-2"><div className="flex items-center justify-between text-xs text-ink-muted"><span>Jami Daromad (Revenue)</span><DollarSign className="w-4 h-4 text-accent" /></div><div className="text-2xl font-bold text-accent">{formatMoney(summary.totalRevenueUzS)}</div><div className="text-xs text-ink-subtle">O'rtacha Chek (AOV): {formatMoney(summary.averageOrderValueUzS)}</div></div>
  <div className="bg-cream border border-border rounded-xl p-5 shadow-sm space-y-2"><div className="flex items-center justify-between text-xs text-ink-muted"><span>Guruhlar To'lishi</span><PieChart className="w-4 h-4 text-accent" /></div><div className="text-2xl font-bold text-ink">{summary.overallFillRate}</div><div className="text-xs text-ink-subtle">Aktiv Talabalar: {summary.activeStudentsCount} nafar</div></div>
  <div className="bg-cream border border-border rounded-xl p-5 shadow-sm space-y-2"><div className="flex items-center justify-between text-xs text-ink-muted"><span>Uy Vazifasi Navbati</span><Clock className="w-4 h-4 text-accent" /></div><div className="text-2xl font-bold text-ink">{summary.pendingHomeworkCount} ta</div><div className="text-xs text-ink-subtle">Tekshirilgan: {summary.reviewedHomeworkCount} ta topshiriq</div></div>
</div>; }
