import { withTransactionLock } from "@/db";
import { trackServerEvent } from "@/features/analytics/server/track";
import { hashOtpCode, normalizePhone, verifyOtpCode } from "@/lib/auth/password";
import { ServiceError } from "@/lib/http/errors";
import type { SendSmsResult } from "@/lib/sms/eskiz";
import type { DbExecutor } from "@/features/payments/server/payments.repository";
import type { AttributionTxStore } from "@/features/referrals/server/attribution.service";
import { attributeReferralFromCookieTx } from "@/features/referrals/server/attribution.service";
import type { AuthSessionRepository } from "./auth-session.repository";
import type { AuthUserRepository } from "./auth-user.repository";
import type { RegistrationRepository } from "./registration.repository";
import type { OtpRepository } from "./otp.repository";
import { toPublicUser, type PublicAuthUser, type SessionSigner } from "./password-auth.service";

export interface OtpSmsSender {
  send(input: { phone: string; code: string }): Promise<SendSmsResult>;
}

export interface OtpSendInput {
  phone: string;
  purpose: string;
  /** CSPRNG 6-digit code generated by the caller (route keeps `randomInt`). */
  code: string;
  isProduction: boolean;
}

export type OtpSendOutcome =
  | { ok: true; expiresAt: Date }
  | { ok: false; reason: "sms_unavailable" };

/**
 * OTP request: stores the code hash, then sends the SMS. The production
 * fail-closed branch is returned as data (not thrown) so the route keeps
 * the exact legacy 503 contract pinned by the hardening test.
 */
export async function requestOtp(
  repo: OtpRepository,
  sender: OtpSmsSender,
  input: OtpSendInput,
): Promise<OtpSendOutcome> {
  const normalizedPhone = normalizePhone(input.phone);
  const expiresAt = new Date(Date.now() + 5 * 60 * 1000);
  await repo.insertOtp({
    phone: normalizedPhone,
    codeHash: hashOtpCode(input.code),
    purpose: input.purpose,
    expiresAt,
  });
  const smsResult = await sender.send({ phone: normalizedPhone, code: input.code });
  if (input.isProduction) {
    if (!smsResult.success || smsResult.mock) return { ok: false, reason: "sms_unavailable" };
  } else if (!smsResult.success) {
    throw new ServiceError("PROVIDER_UNAVAILABLE", smsResult.error || "SMS yuborishda xatolik yuz berdi.", 500);
  }
  return { ok: true, expiresAt };
}

export interface OtpVerifyInput {
  phone: string;
  code: string;
  fullName?: string;
  purpose: string;
  /** Raw `ref_code` cookie value (null when absent). New users only. */
  refCode: string;
  ip?: string;
  userAgent?: string;
}

export interface OtpVerifyOutcome {
  user: PublicAuthUser;
  token: string;
  expiresAt: Date;
  refCodeAttributed: boolean;
}

const SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000;

/**
 * OTP verification: attempts accounting + single-use marking stay exactly
 * as the legacy route did; new-user registration (user + profile +
 * referral attribution) runs in one advisory-locked transaction.
 */
export async function verifyOtp(
  otpRepo: OtpRepository,
  users: AuthUserRepository,
  sessionsRepo: AuthSessionRepository,
  referrals: AttributionTxStore,
  registration: RegistrationRepository,
  signer: SessionSigner,
  input: OtpVerifyInput,
): Promise<OtpVerifyOutcome> {
  const normalizedPhone = normalizePhone(input.phone);
  const record = await otpRepo.findActiveOtp(normalizedPhone, input.purpose, new Date());
  if (!record) {
    throw new ServiceError(
      "OTP_NOT_FOUND",
      "SMS kod topilmadi, muddati o'tgan yoki urinishlar soni tugagan",
      400,
    );
  }
  await otpRepo.bumpAttempts(record.id, record.attempts + 1);
  if (!verifyOtpCode(input.code, record.codeHash)) {
    throw new ServiceError("INVALID_OTP", "SMS kod noto'g'ri", 400);
  }
  await otpRepo.markUsed(record.id, new Date());

  let user = await users.findByPhone(normalizedPhone);
  const isNewUser = !user;
  let refCodeAttributed = false;
  if (user) {
    // Single update: last-login touch plus first-name fill for placeholder names.
    const patch: { lastLoginAt: Date; fullName?: string } = { lastLoginAt: new Date() };
    let nextFullName = user.fullName;
    if (input.fullName && (user.fullName === "Foydalanuvchi" || !user.fullName)) {
      patch.fullName = input.fullName;
      nextFullName = input.fullName;
    }
    await withTransactionLock(`otp-touch:${user.id}`, async (tx) => {
      const ex = tx as DbExecutor | null | undefined;
      if (!ex) throw new ServiceError("PROVIDER_UNAVAILABLE", "Ma'lumotlar bazasi tranzaksiyasi mavjud emas", 503);
      await users.updateLoginFieldsTx(ex, user!.id, patch);
    });
    if (nextFullName !== user.fullName) user = { ...user, fullName: nextFullName };
  } else {
    type RegistrationOutcome = { userId: string; attributed: boolean };
    const completed = await withTransactionLock<RegistrationOutcome>(
      `registration:${normalizedPhone}`,
      async (tx) => {
        const ex = tx as DbExecutor | null | undefined;
        if (!ex) throw new ServiceError("PROVIDER_UNAVAILABLE", "Ma'lumotlar bazasi tranzaksiyasi mavjud emas", 503);
        const created = await registration.createUserTx(ex, {
          phone: normalizedPhone,
          fullName: input.fullName || "Foydalanuvchi",
        });
        await registration.createProfileTx(ex, created.id);
        const attribution = await attributeReferralFromCookieTx(referrals, ex, {
          code: input.refCode,
          referredUserId: created.id,
        });
        return { userId: created.id, attributed: attribution.attributed };
      },
    );
    const created = await users.findById(completed.userId);
    if (!created) throw new ServiceError("NOT_FOUND", "Foydalanuvchi topilmadi", 404);
    user = created;
    refCodeAttributed = completed.attributed;
  }

  void trackServerEvent({
    type: isNewUser ? "signup" : "login",
    userId: user.id,
    path: "/api/auth/otp/verify",
    props: { method: isNewUser ? "otp_registration" : "otp_login" },
  });

  const expiresAt = new Date(Date.now() + SESSION_TTL_MS);
  // Single write outside the registration tx (W4-ARCH: single write, fine).
  const createdSession = await sessionsRepo.createSession({
    userId: user.id,
    expiresAt,
    userAgent: input.userAgent,
    ip: input.ip,
  });
  const sessionId = createdSession?.id ?? user.id;

  const token = await signer.sign({
    sessionId,
    userId: user.id,
    role: user.role,
    expiresAt: expiresAt.getTime(),
  });
  return { user: toPublicUser(user), token, expiresAt, refCodeAttributed };
}
