"use client";

import { Filter, HelpCircle, Plus, Search, UserCheck, PhoneCall, DollarSign, AlertCircle, CheckCircle2, MoveRight, Pencil, Trash2, Clock } from "lucide-react";
import { LeadColumn, type PipelineStage } from "./LeadColumn";
import type { Lead, LeadStatus } from "./types";

export const PIPELINE_STAGES: PipelineStage[] = [{ id: "new", title: "Yangi (New)", badgeBg: "bg-blue-500/10 border-blue-500/30", badgeText: "text-blue-600 dark:text-blue-400", icon: HelpCircle }, { id: "contacted", title: "Bog'lanildi (Contacted)", badgeBg: "bg-amber-500/10 border-amber-500/30", badgeText: "text-amber-600 dark:text-amber-400", icon: PhoneCall }, { id: "consultation", title: "Konsultatsiya (Consultation)", badgeBg: "bg-purple-500/10 border-purple-500/30", badgeText: "text-purple-600 dark:text-purple-400", icon: UserCheck }, { id: "paid", title: "To'langan (Paid)", badgeBg: "bg-emerald-500/10 border-emerald-500/30", badgeText: "text-emerald-600 dark:text-emerald-400", icon: DollarSign }];
type Props = { leads: Lead[]; draggedLeadId: string | null; onDragStart: (event: React.DragEvent, id: string) => void; onDragOver: (event: React.DragEvent) => void; onDrop: (event: React.DragEvent, status: LeadStatus) => void; onEdit: (lead: Lead) => void; onDelete: (id: string) => void; onMove: (id: string, status: LeadStatus) => void; onQuiz: (lead: Lead) => void };
export function KanbanBoard({ leads, draggedLeadId, onDragStart, onDragOver, onDrop, onEdit, onDelete, onMove, onQuiz }: Props) { return <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">{PIPELINE_STAGES.map((stage) => <LeadColumn key={stage.id} stage={stage} leads={leads.filter((lead) => lead.status === stage.id)} draggedLeadId={draggedLeadId} onDragStart={onDragStart} onDragOver={onDragOver} onDrop={onDrop} onEdit={onEdit} onDelete={onDelete} onMove={onMove} onQuiz={onQuiz} />)}</div>; }
