"use client";

import { Clock, HelpCircle, Pencil, Phone, Trash2 } from "lucide-react";
import type { Lead, LeadStatus } from "./types";

type Props = { lead: Lead; dragged: boolean; onDragStart: (event: React.DragEvent, id: string) => void; onEdit: (lead: Lead) => void; onDelete: (id: string) => void; onMove: (id: string, status: LeadStatus) => void; onQuiz: (lead: Lead) => void; sourceClass: string };
export function LeadCard({ lead, dragged, onDragStart, onEdit, onDelete, onMove, onQuiz, sourceClass }: Props) {
  return <div draggable onDragStart={(e) => onDragStart(e, lead.id)} className={`bg-cream border border-border rounded-lg p-3.5 shadow-sm hover:shadow-md transition-all cursor-grab active:cursor-grabbing space-y-3 ${dragged ? "opacity-50 border-accent" : ""}`}>
    <div className="flex items-start justify-between"><div><h5 className="font-semibold text-sm text-ink leading-tight">{lead.name}</h5><a href={`tel:${lead.phone}`} className="inline-flex items-center text-xs text-accent hover:underline mt-1"><Phone className="w-3 h-3 mr-1" />{lead.phone}</a></div><span className={`text-[10px] px-2 py-0.5 rounded-full font-medium border ${sourceClass}`}>{lead.source}</span></div>
    {lead.recommendedCourseTitle && <div className="text-xs px-2.5 py-1 bg-cream-warm border border-border rounded-md text-ink-muted">🎯 {lead.recommendedCourseTitle}</div>}
    {lead.quizAnswers && <button onClick={() => onQuiz(lead)} className="text-[11px] text-purple-600 dark:text-purple-400 hover:underline flex items-center"><HelpCircle className="w-3 h-3 mr-1" />Quiz javoblarini ko'rish</button>}
    <div className="pt-2 border-t border-border flex items-center justify-between text-xs text-ink-subtle"><span className="flex items-center text-[10px]"><Clock className="w-3 h-3 mr-1 text-ink-subtle" />{new Date(lead.createdAt).toLocaleDateString("uz-UZ", { month: "short", day: "numeric" })}</span><div className="flex items-center space-x-1"><select value={lead.status} onChange={(e) => onMove(lead.id, e.target.value as LeadStatus)} className="text-[11px] bg-cream-warm border border-border rounded px-1.5 py-0.5 text-ink focus:outline-none" title="Bosqichni o'zgartirish"><option value="new">Yangi</option><option value="contacted">Bog'lanildi</option><option value="consultation">Konsultatsiya</option><option value="paid">To'langan</option><option value="rejected">Rad etildi</option></select><button onClick={() => onEdit(lead)} className="p-1 hover:text-ink text-ink-muted rounded transition-colors" title="Tahrirlash"><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => onDelete(lead.id)} className="p-1 hover:text-red-500 text-ink-muted rounded transition-colors" title="O'chirish"><Trash2 className="w-3.5 h-3.5" /></button></div></div>
  </div>;
}
export function sourceBadge(source: string) { switch (source) { case "quiz": return "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20"; case "free_lesson": return "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20"; case "telegram": return "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20"; case "form": return "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20"; default: return "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20"; } }
