import type { Metadata } from "next";
import { BadgeCheck, Wrench } from "lucide-react";
import { Container, Eyebrow, Heading } from "@/components/ui";
import { Card } from "@/components/ui/Surfaces";
import { NextStepCTA } from "@/components/ui/NextStepCTA";

export const metadata: Metadata = { title: "Ekspertlar va bitiruvchilar", description: "Naqsh mentorlik yo‘nalishlari va namuna profillari haqida." };
const experts = [{ name: "Namuna profil 1", role: "SaaS va botlar yo‘nalishi", skills: ["Claude Code", "Next.js", "Telegram Bot API"] }, { name: "Namuna profil 2", role: "Prompt va avtomatlashtirish", skills: ["Prompt engineering", "Make.com", "Zod"] }];
export default function Page() { return <div className="bg-bg text-ink"><Container className="py-20 sm:py-28"><Eyebrow>Hamjamiyat namunasi</Eyebrow><Heading as="h1" className="mt-3">Kurs jamoasi va mentorlik yo‘nalishlari</Heading><p className="mt-4 max-w-2xl text-lg text-ink-muted">Quyidagi profillar namuna ko‘rinishida berilgan. Haqiqiy ishtirokchi ma’lumotlari faqat rozik va tekshirilgan holda qo‘shiladi.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{experts.map(expert => <Card key={expert.name}><div className="flex items-start justify-between gap-4"><div><Heading as="h2" className="text-2xl">{expert.name}</Heading><p className="mt-1 text-sm font-semibold text-accent">{expert.role}</p></div><BadgeCheck className="size-6 shrink-0 text-accent" aria-label="Namuna profil" /></div><div className="mt-6 flex flex-wrap gap-2">{expert.skills.map(skill => <span key={skill} className="inline-flex items-center gap-1 rounded-md border border-border bg-bg-sunken px-3 py-1.5 font-mono text-xs text-ink-muted"><Wrench className="size-3" aria-hidden="true" />{skill}</span>)}</div><p className="mt-6 border-t border-border pt-4 text-sm leading-relaxed text-ink-muted">Bu namuna ma’lumot emas. Haqiqiy profil uchun ism, rol va kontaktlar rozik bilan tasdiqlanadi.</p></Card>)}</div></Container><NextStepCTA title="Siz ham o‘z loyihangizni quring" /></div>; }
