"use client";
import { useState } from "react";
import { CheckCircle, Clock, Edit, FileText, Plus } from "lucide-react";
import { BlogFilters } from "./Blogs/BlogFilters";
import { BlogFormModal } from "./Blogs/BlogFormModal";
import { BlogTable } from "./Blogs/BlogTable";
import { useBlogs } from "./Blogs/useBlogs";
import type { BlogForm, BlogPost, EditorTab } from "./Blogs/types";
const blank = (): BlogForm => ({ title: "", slug: "", category: "Vibe Coding", authorName: "Mirzo Academy Team", coverUrl: "", excerpt: "", contentMd: "", seoTitle: "", seoDescription: "", status: "published", publishedAt: new Date().toISOString().slice(0, 16) });
export type { BlogPost } from "./Blogs/types";
export function BlogManager() {
  const data = useBlogs(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<BlogPost | null>(null); const [form, setForm] = useState<BlogForm>(blank); const [tab, setTab] = useState<EditorTab>("edit");
  const openCreate = () => { setEditing(null); setForm(blank()); setTab("edit"); setOpen(true); };
  const openEdit = (post: BlogPost) => { setEditing(post); setForm({ title: post.title, slug: post.slug, category: post.category, authorName: post.authorName, coverUrl: post.coverUrl || "", excerpt: post.excerpt || "", contentMd: post.contentMd, seoTitle: post.seoTitle || "", seoDescription: post.seoDescription || "", status: post.status, publishedAt: new Date(post.publishedAt).toISOString().slice(0, 16) }); setTab("edit"); setOpen(true); };
  const insert = (prefix: string, suffix = "", defaultText = "matn") => { const el = document.getElementById("blog-content-textarea") as HTMLTextAreaElement | null; if (!el) return setForm(p => ({ ...p, contentMd: p.contentMd + `${prefix}${defaultText}${suffix}` })); const start = el.selectionStart; const end = el.selectionEnd; const selected = form.contentMd.substring(start, end) || defaultText; setForm(p => ({ ...p, contentMd: p.contentMd.substring(0, start) + `${prefix}${selected}${suffix}` + p.contentMd.substring(end) })); window.setTimeout(() => { el.focus(); el.setSelectionRange(start + prefix.length, start + prefix.length + selected.length); }, 50); };
  const stats = { total: data.posts.length, published: data.posts.filter(p => p.status === "published").length, scheduled: data.posts.filter(p => p.status === "scheduled").length, drafts: data.posts.filter(p => p.status === "draft").length };
  return <div className="space-y-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-ink flex items-center gap-2"><FileText className="w-6 h-6 text-accent" />Blog CMS & Maqolalar Boshqaruvi</h1><p className="text-sm text-ink-muted mt-1">Platforma blogidagi barcha maqolalarni tahrirlash, SEO moslashtirish va rejalashtirilgan chop etish.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center px-4 py-2.5 rounded-lg bg-accent text-ink font-medium text-sm hover:bg-accent/90 transition-colors shadow-sm gap-2"><Plus className="w-4 h-4" />Yangi Maqola Yaratish</button></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><div className="bg-bg-sunken border border-border rounded-xl p-4"><div className="text-xs font-medium text-ink-muted">Jami Maqolalar</div><div className="text-2xl font-bold text-ink mt-1">{stats.total}</div></div><div className="bg-bg-sunken border border-border rounded-xl p-4"><div className="text-xs font-medium text-success flex items-center gap-1"><CheckCircle className="w-3.5 h-3.5" /> Published</div><div className="text-2xl font-bold text-ink mt-1">{stats.published}</div></div><div className="bg-bg-sunken border border-border rounded-xl p-4"><div className="text-xs font-medium text-brand flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> Rejalashtirilgan</div><div className="text-2xl font-bold text-ink mt-1">{stats.scheduled}</div></div><div className="bg-bg-sunken border border-border rounded-xl p-4"><div className="text-xs font-medium text-gold flex items-center gap-1"><Edit className="w-3.5 h-3.5" /> Qoralamalar</div><div className="text-2xl font-bold text-ink mt-1">{stats.drafts}</div></div></div>
    <BlogFilters search={data.search} setSearch={data.setSearch} statusFilter={data.statusFilter} setStatusFilter={data.setStatusFilter} /><BlogTable posts={data.posts} loading={data.loading} onEdit={openEdit} onDelete={data.remove} />{open ? <BlogFormModal form={form} setForm={setForm} editing={editing} onClose={() => setOpen(false)} onSave={async e => { e.preventDefault(); if (await data.save(form, editing)) setOpen(false); }} saving={data.saving} tab={tab} setTab={setTab} insert={insert} /> : null}
  </div>;
}
