"use client";
import { useState } from "react";
import { Send } from "lucide-react";
import { NotificationComposer } from "./Notifications/NotificationComposer";
import { NotificationList } from "./Notifications/NotificationList";
import { TelegramPreview } from "./Notifications/TelegramPreview";
import { useNotifications } from "./Notifications/useNotifications";
import type { NotificationAudience, NotificationChannel } from "./Notifications/types";
export type { BroadcastItem } from "./Notifications/types";
export function NotificationManager() { const data = useNotifications(); const [title, setTitle] = useState(""); const [channel, setChannel] = useState<NotificationChannel>("telegram"); const [audience, setAudience] = useState<NotificationAudience>("all_users"); const [cohortId, setCohortId] = useState(""); const [body, setBody] = useState("Assalomu alaykum {{fullName}}! Vibe Coding kursimizning navbatdagi moduli jonli darsi 19:00 da boshlanadi. Darsga kirish: {{loginUrl}}"); const send = (s: "sent" | "draft") => data.send(title, channel, audience, cohortId, body, s); return <div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight text-ink flex items-center gap-2"><Send className="w-6 h-6 text-accent" />Ommaviy Xabarnomalar (Broadcast Composer)</h1><p className="text-sm text-ink-muted mt-1">Telegram bot, Email va SMS orqali talabalar va leadlarga maqsadli (targeted) bildirishnomalar yuborish.</p></div><div className="grid grid-cols-1 lg:grid-cols-12 gap-6"><NotificationComposer cohorts={data.cohorts} sending={data.sending} onSend={send} title={title} setTitle={setTitle} channel={channel} setChannel={setChannel} audience={audience} setAudience={setAudience} cohortId={cohortId} setCohortId={setCohortId} body={body} setBody={setBody} /><div className="lg:col-span-5 space-y-4"><TelegramPreview channel={channel} title={title} messageBody={body} targetAudience={audience} /></div></div><NotificationList broadcasts={data.broadcasts} loading={data.loading} /></div>; }
