import { z } from "zod";
import { drizzleAnalyticsRepository } from "@/features/analytics/server/analytics.repository";
import { getStudents } from "@/features/analytics/server/business.service";
import { conversationPatchSchema } from "@/features/chat/contracts";
import { getThread, listConversations, postReply, updateConversation } from "@/features/chat/server/chat.service";
import { leadsList, updateLeadStatus } from "../server/leads.repository";
import { listStudents, studentProfile } from "../server/students.repository";
import { paymentsList, refundsList, salesByCourse } from "../server/commerce.repository";
import { decodeCursor, encodeCursor, maskPhone } from "../server/pagination";
import { dateRangeInputSchema, dateRangeShape, cursorInputSchema, cursorShape, uuidInputSchema } from "../contracts";
import { result, toolError, type ToolDefinition } from "./types";

const date = (input: unknown) => { const parsed = dateRangeInputSchema.parse(input); return { from: new Date(parsed.from), to: new Date(parsed.to), granularity: parsed.granularity, compare: true }; };
const simple = (name: string, title: string, description: string, scope: string, inputShape: ToolDefinition["inputShape"], handler: ToolDefinition["handler"], readOnly = true): ToolDefinition => ({ name, title, description, scope, inputShape, readOnly, destructive: false, handler });
const fail = (error: unknown, title: string) => toolError(error, title);

export const peopleTools: ToolDefinition[] = [
  simple("students_list", "Talabalar ro'yxati", "Talabalar ro'yxati; telefon va email standart PII flag'siz masklangan.", "students:read", { ...cursorShape, search: z.string().trim().max(100).optional() }, async (input, context) => { try { const parsed = cursorInputSchema.extend({ search: z.string().trim().max(100).optional() }).parse(input); const data = await listStudents(parsed, context.principal.scopes.includes("students:read:pii")); return { result: result("Talabalar ro'yxati tayyor.", data, null, null, data.nextCursor), title: "Talabalar" }; } catch (error) { return fail(error, "Talabalar"); } }),
  simple("student_profile", "Talaba profili", "Talaba progress, uy vazifalari va to'lovlari; maxfiy ma'lumot qaytarilmaydi.", "students:read", uuidInputSchema.shape, async (input, context) => { try { const { id } = uuidInputSchema.parse(input); const data = await studentProfile(id, context.principal.scopes.includes("students:read:pii")); if (!data) return { result: result("Talaba topilmadi.", { found: false }), title: "Talaba profili" }; return { result: result("Talaba profili tayyor.", data), title: "Talaba profili" }; } catch (error) { return fail(error, "Talaba profili"); } }),
  simple("course_completion", "Kurs tugash statistikasi", "Kurslar bo'yicha boshlanish va tugash ulushi.", "students:read", dateRangeShape, async (input) => { try { const report = await getStudents(drizzleAnalyticsRepository, date(input)); return { result: result(report.summary, { courses: report.courses, summary: report.summary }, null, null), title: "Kurs tugash statistikasi" }; } catch (error) { return fail(error, "Kurs tugash statistikasi"); } }),
  simple("lesson_dropoff", "Darsdan chiqish", "Eng ko'p tashlab ketilgan darslar.", "students:read", dateRangeShape, async (input) => { try { const report = await getStudents(drizzleAnalyticsRepository, date(input)); const rows = report.courses.filter((course) => course.dropOffLesson).map((course) => ({ course: course.courseTitle, lesson: course.dropOffLesson, dropOffCount: course.dropOffCount })); return { result: result(report.summary, { courses: rows }, null, null), title: "Darsdan chiqish" }; } catch (error) { return fail(error, "Darsdan chiqish"); } }),
  simple("cohort_attendance", "Kohort qatnashuvi", "Kohort qatnashuv ulushi va tarif.", "students:read", dateRangeShape, async (input) => { try { const report = await getStudents(drizzleAnalyticsRepository, date(input)); return { result: result(report.summary, { rate: report.cohortAttendanceRate, definition: report.attendanceDefinition }), title: "Kohort qatnashuvi" }; } catch (error) { return fail(error, "Kohort qatnashuvi"); } }),
  simple("sales_summary", "Savdo umumiy ko'rsatkichlari", "Kunlik savdo, to'lovlar va qaytarishlar.", "sales:read", dateRangeShape, async (input) => { try { const { getSales } = await import("@/features/analytics/server/business.service"); const report = await getSales(drizzleAnalyticsRepository, date(input)); return { result: result(report.summary, report), title: "Savdo umumiy ko'rsatkichlari" }; } catch (error) { return fail(error, "Savdo umumiy ko'rsatkichlari"); } }),
  simple("sales_by_course", "Kurslar savdosi", "Kurslar bo'yicha to'lovlar soni va tushumi.", "sales:read", dateRangeShape, async (input) => { try { const value = date(input); const rows = await salesByCourse(value.from, value.to); return { result: result("Kurslar savdosi tayyor.", { courses: rows }), title: "Kurslar savdosi" }; } catch (error) { return fail(error, "Kurslar savdosi"); } }),
  simple("payments_list", "To'lovlar", "Oxirgi to'lovlar; maxfiy metama'lumot chiqarilmaydi.", "sales:read", { ...cursorShape, from: z.string().datetime().optional(), to: z.string().datetime().optional(), status: z.enum(["pending", "paid", "failed", "refunded"]).optional() }, async (input) => { try { const data = await paymentsList(cursorInputSchema.extend({ from: z.string().datetime().optional(), to: z.string().datetime().optional(), status: z.enum(["pending", "paid", "failed", "refunded"]).optional() }).parse(input)); return { result: result("To'lovlar ro'yxati tayyor.", data, null, null, data.nextCursor), title: "To'lovlar" }; } catch (error) { return fail(error, "To'lovlar"); } }),
  simple("refunds_list", "Qaytarishlar", "Qaytarish so'rovlari va ularning holati.", "sales:read", { ...cursorShape, status: z.enum(["pending", "approved", "paid", "rejected"]).optional() }, async (input) => { try { const data = await refundsList(cursorInputSchema.extend({ status: z.enum(["pending", "approved", "paid", "rejected"]).optional() }).parse(input)); return { result: result("Qaytarishlar ro'yxati tayyor.", data, null, null, data.nextCursor), title: "Qaytarishlar" }; } catch (error) { return fail(error, "Qaytarishlar"); } }),
];

export const leadTools: ToolDefinition[] = [
  simple("leads_list", "Leadlar", "Leadlar holati va manbalari; kontaktlar masklangan.", "analytics:read", { ...cursorShape, status: z.enum(["new", "contacted", "qualified", "won", "lost"]).optional(), search: z.string().trim().max(100).optional() }, async (input, context) => { try { const parsed = cursorInputSchema.extend({ status: z.enum(["new", "contacted", "qualified", "won", "lost"]).optional(), search: z.string().trim().max(100).optional() }).parse(input); const data = await leadsList(parsed, context.principal.scopes.includes("students:read:pii")); return { result: result("Leadlar ro'yxati tayyor.", data, null, null, data.nextCursor), title: "Leadlar" }; } catch (error) { return fail(error, "Leadlar"); } }),
  { ...simple("lead_update_status", "Lead holatini yangilash", "Lead holatini o'zgartiradi; bu write tool audit qilinadi.", "leads:write", { id: z.string().uuid(), status: z.enum(["new", "contacted", "qualified", "won", "lost"]) }, async (input, context) => { try { const parsed = z.object({ id: z.string().uuid(), status: z.enum(["new", "contacted", "qualified", "won", "lost"]) }).parse(input); const data = await updateLeadStatus(parsed.id, parsed.status, context.principal.userId); return { result: result("Lead holati yangilandi.", data), title: "Lead holati" }; } catch (error) { return fail(error, "Lead holati"); } }, false) },
];

export const chatTools: ToolDefinition[] = [
  simple("chat_list_open", "Ochiq suhbatlar", "Ochiq suhbatlar; kontaktlar PII flag'siz masklangan.", "chat:read", { ...cursorShape, q: z.string().trim().max(100).optional() }, async (input, context) => { try { const parsed = cursorInputSchema.extend({ q: z.string().trim().max(100).optional() }).parse(input); const all = await listConversations(context.principal.userId, "open", parsed.q ?? ""); const offset = decodeCursor(parsed.cursor); const rows = all.slice(offset, offset + parsed.limit).map((row) => ({ ...row, contactPhone: maskPhone(row.contactPhone, context.principal.scopes.includes("students:read:pii")), contactTelegram: context.principal.scopes.includes("students:read:pii") ? row.contactTelegram : null })); return { result: result("Ochiq suhbatlar tayyor.", { conversations: rows }, null, null, offset + rows.length < all.length ? encodeCursor(offset + rows.length) : null), title: "Ochiq suhbatlar" }; } catch (error) { return fail(error, "Ochiq suhbatlar"); } }),
  simple("chat_thread", "Suhbat tarixi", "Suhbat xabarlari; maxfiy visitor token qaytarilmaydi.", "chat:read", z.object({ id: z.string().uuid() }).shape, async (input, context) => { try { const { id } = z.object({ id: z.string().uuid() }).parse(input); const thread = await getThread(id); return { result: result("Suhbat tarixi tayyor.", { ...thread, conversation: { ...thread.conversation, contactPhone: maskPhone(thread.conversation.contactPhone, context.principal.scopes.includes("students:read:pii")), contactTelegram: context.principal.scopes.includes("students:read:pii") ? thread.conversation.contactTelegram : null } }), title: "Suhbat tarixi" }; } catch (error) { return fail(error, "Suhbat tarixi"); } }),
  { ...simple("chat_reply", "Suhbatga javob", "Suhbatga admin yoki AI sifatida javob yozadi; idempotent clientId qabul qilinadi.", "chat:write", { conversationId: z.string().uuid(), body: z.string().trim().min(1).max(2000), clientId: z.string().uuid().optional() }, async (input, context) => { try { const parsed = z.object({ conversationId: z.string().uuid(), body: z.string().trim().min(1).max(2000), clientId: z.string().uuid().optional() }).parse(input); const message = await postReply(context.principal.userId, parsed.conversationId, parsed.body, parsed.clientId ?? crypto.randomUUID(), undefined, null, context.principal.sender); return { result: result("Javob yuborildi.", { message, sender: context.principal.sender }), title: "Suhbatga javob" }; } catch (error) { return fail(error, "Suhbatga javob"); } }, false) },
  { ...simple("chat_set_mode", "Suhbat AI rejimi", "Suhbat AI rejimini o'zgartiradi: off, assist yoki auto.", "chat:write", { conversationId: z.string().uuid(), aiMode: z.enum(["off", "assist", "auto"]) }, async (input, context) => { try { const parsed = z.object({ conversationId: z.string().uuid(), aiMode: z.enum(["off", "assist", "auto"]) }).parse(input); const data = await updateConversation(context.principal.userId, conversationPatchSchema.parse(parsed)); return { result: result("Suhbat rejimi yangilandi.", data), title: "Suhbat rejimi" }; } catch (error) { return fail(error, "Suhbat rejimi"); } }, false) },
];
