import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { siteConfig } from "@/lib/siteConfig";
import { mcpToolMap, mcpToolRegistry, toolOutputShape } from "./index";
import type { McpPrincipal } from "../server/auth.service";
import { svgFor } from "./visual";

const UI_HTML = (kind: string): string => `<!doctype html><html lang="uz"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>:root{color-scheme:light dark}body{font:16px system-ui;margin:0;padding:18px;background:Canvas;color:CanvasText}header{display:flex;justify-content:space-between;gap:12px}h1{font-size:20px;margin:0}.card{border:1px solid color-mix(in srgb,CanvasText 20%,transparent);border-radius:16px;padding:16px;margin-top:16px;background:color-mix(in srgb,CanvasText 4%,Canvas)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.value{font-size:26px;font-weight:700}.bar{height:10px;background:color-mix(in srgb,CanvasText 12%,transparent);border-radius:99px;overflow:hidden}.bar>i{display:block;height:100%;background:AccentColor}button{min-height:44px;border:1px solid color-mix(in srgb,CanvasText 25%,transparent);border-radius:10px;background:Canvas;color:CanvasText;padding:0 12px}</style><main><header><h1>Naqsh · ${kind}</h1><button id="refresh">Yangilash</button></header><p id="summary">MCP Apps hostidan ma'lumot kutilmoqda…</p><div id="root" class="grid"></div></main><script>const root=document.getElementById('root');function render(v){if(!v||typeof v!=='object')return;root.textContent='';const data=v.data||v;const items=Array.isArray(data)?data.slice(0,24):Object.entries(data).map(([label,value])=>({label,value}));items.slice(0,24).forEach(x=>{const d=document.createElement('article');d.className='card';d.innerHTML='<div class="value"></div><div class="bar"><i></i></div><small></small>';d.querySelector('.value').textContent=String(x.value??x.count??x.current??'—');d.querySelector('small').textContent=String(x.label??x.title??x.path??'');const max=Math.max(1,...items.map(y=>Number(y.value??y.count??y.current??0)));d.querySelector('i').style.width=Math.max(3,Number(x.value??x.count??x.current??0)/max*100)+'%';root.append(d)});if(v.summary)document.getElementById('summary').textContent=v.summary}addEventListener('message',e=>{const d=e.data||{};if(d.structuredContent||d.result?.structuredContent)render(d.structuredContent||d.result.structuredContent)});document.getElementById('refresh').onclick=()=>postMessage({type:'mcp/ui/tool-call',tool:'analytics_overview',arguments:{from:new Date(Date.now()-30*86400000).toISOString(),to:new Date().toISOString()}},'*');</script></html>`;

function resourceText(uri: string): string { if (uri === "naqsh://courses") return JSON.stringify(Object.entries(siteConfig.courses).map(([slug, value]) => ({ slug, ...value })), null, 2); if (uri === "naqsh://pricing") return JSON.stringify(siteConfig.courses, null, 2); return JSON.stringify({ visitors: "Unique visitor hashes in range", sessions: "30-minute sessions", pageViews: "Page view events", leads: "lead_created events", revenueUzs: "Successful payment values in UZS", completionRate: "Completed lesson progress / started lesson progress", cohortAttendanceRate: "lesson_start attendance / active cohort enrollment", exitRate: "Exits divided by visitors on a page" }, null, 2); }

export function createMcpServer(principal: McpPrincipal): McpServer {
  const server = new McpServer({ name: "naqsh-mcp", version: "2.0.0", websiteUrl: siteConfig.siteUrl });
  for (const tool of mcpToolRegistry) server.registerTool(tool.name, { title: tool.title, description: tool.description, inputSchema: tool.inputShape, outputSchema: toolOutputShape, annotations: { readOnlyHint: tool.readOnly, destructiveHint: tool.destructive, idempotentHint: tool.readOnly, openWorldHint: false }, _meta: tool.ui ? { ui: { resourceUri: tool.ui === "dashboard" ? "ui://naqsh/dashboard" : `ui://naqsh/chart/${tool.ui}`, visibility: ["model", "app"] } } : undefined }, async (input) => { if (!principal.scopes.some((scope) => scope === tool.scope)) return { content: [{ type: "text", text: "Bu amal uchun ruxsat yetarli emas." }], isError: true }; const run = await tool.handler(input, { principal }); const content: Array<{ type: "text"; text: string } | { type: "image"; data: string; mimeType: string }> = [{ type: "text", text: run.result.summary }]; if (run.result.markdown) content.push({ type: "text", text: run.result.markdown }); if (run.imageSvg) content.push({ type: "image", data: Buffer.from(run.imageSvg).toString("base64"), mimeType: "image/svg+xml" }); return { content, structuredContent: run.result }; });
  for (const kind of ["dashboard", "line", "bar", "funnel", "table", "kpi"]) server.registerResource(`naqsh-chart-${kind}`, kind === "dashboard" ? "ui://naqsh/dashboard" : `ui://naqsh/chart/${kind}`, { title: `Naqsh ${kind}`, description: "Naqsh uslubidagi interaktiv grafik", mimeType: "text/html;profile=mcp-app" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "text/html;profile=mcp-app", text: UI_HTML(kind), _meta: { ui: { csp: { connectDomains: [], resourceDomains: [], frameDomains: [] }, prefersBorder: true } } }] }));
  server.registerResource("naqsh-courses", "naqsh://courses", { title: "Naqsh kurslari", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: resourceText(uri.href) }] }));
  server.registerResource("naqsh-pricing", "naqsh://pricing", { title: "Naqsh narxlari", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: resourceText(uri.href) }] }));
  server.registerResource("naqsh-metrics-glossary", "naqsh://metrics-glossary", { title: "Metrikalar lug'ati", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: resourceText(uri.href) }] }));
  const prompt = (name: string, title: string, text: string) => server.registerPrompt(name, { title }, async () => ({ messages: [{ role: "user", content: { type: "text", text } }] }));
  prompt("haftalik_hisobot", "Haftalik hisobot", "Naqsh haftalik hisobotini tayyorla: analytics_overview, analytics_timeseries va analytics_funnel ni chaqir; natijani qisqa Markdown jadval, chartSpec va xulosa bilan taqdim et. Vaqt oralig'ini oldingi 7 kunga tengla.");
  prompt("sotuv_tahlili", "Sotuv tahlili", "Sotuvni tahlil qil: sales_summary va sales_by_course ni chaqir, funnel bilan solishtir, konversiya tushishgan joylarni aniq ko'rsat. Hech qanday taxminiy raqam yozma.");
  prompt("talabalar_holati", "Talabalar holati", "Talabalar holatini xavfsiz tahlil qil: students_list va course_completion ni chaqir. Telefon/email ni faqat students:read:pii ruxsati bo'lsa ko'rsat.");
  prompt("marketing_manbalari", "Marketing manbalari", "Marketing manbalarini tahlil qil: analytics_acquisition va analytics_behaviour ni chaqir, manba, landing page va chiqish sahifalarini jadval qilib ber. Marketing tavsiyasini faqat dalildan kelib chiqib yoz.");
  return server;
}

export { mcpToolMap };
