"use client";
import { useCallback, useEffect, useState } from "react";
import type { ActivityKpis, ActivityStatus, StudentActivityItem } from "./types";
const initial: ActivityKpis = { totalStudents: 0, activeStudents: 0, atRiskStudents: 0, completedStudents: 0, avgProgressPercent: 0, pendingHomeworkCount: 0 };
export function useActivity() { const [students, setStudents] = useState<StudentActivityItem[]>([]); const [kpis, setKpis] = useState<ActivityKpis>(initial); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState<ActivityStatus | "all">("all"); const [cohortFilter, setCohortFilter] = useState("");
  const fetchStudentActivity = useCallback(async () => { setLoading(true); try { const p = new URLSearchParams(); if (search) p.append("search", search); if (statusFilter !== "all") p.append("status", statusFilter); if (cohortFilter) p.append("cohortId", cohortFilter); const res = await fetch(`/api/admin/students/activity?${p}`); const data: unknown = await res.json(); if (typeof data === "object" && data && "success" in data && data.success) { if ("students" in data && Array.isArray(data.students)) setStudents(data.students as StudentActivityItem[]); if ("kpis" in data && data.kpis) setKpis(data.kpis as ActivityKpis); } } catch (e) { console.error("Failed to fetch student activity:", e); } finally { setLoading(false); } }, [search, statusFilter, cohortFilter]);
  useEffect(() => { void fetchStudentActivity(); }, [fetchStudentActivity]); return { students, kpis, loading, search, setSearch, statusFilter, setStatusFilter, cohortFilter, setCohortFilter, fetchStudentActivity };
}
export function formatLastActive(isoString: string) { try { const date = new Date(isoString); const diffMinutes = Math.floor((Date.now() - date.getTime()) / 60000); if (diffMinutes < 1) return "Hozirgina online"; if (diffMinutes < 60) return `${diffMinutes} daqiqa oldin`; const h = Math.floor(diffMinutes / 60); if (h < 24) return `${h} soat oldin`; const d = Math.floor(h / 24); if (d === 1) return "Kechagi kunda"; if (d < 30) return `${d} kun oldin`; return date.toLocaleDateString("uz-UZ", { month: "short", day: "numeric" }); } catch { return isoString; } }
export function statusBadgeStyle(status: ActivityStatus) { return status === "active" ? "bg-success-soft text-success border-success/30 font-semibold" : status === "at_risk" ? "bg-accent-soft text-accent border-accent-line font-semibold" : status === "completed" ? "bg-cream-deep text-ink border-border font-semibold" : "bg-cream-warm text-ink-muted border-border"; }
export function statusLabel(status: ActivityStatus) { return status === "active" ? "Faol" : status === "at_risk" ? "Xavf ostida" : status === "completed" ? "Bitirgan" : "Passiv"; }
