const esc = (value: string): string => value.replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[char] ?? char);
const field = (name: string, value: string): string => `<input type="hidden" name="${name}" value="${esc(value)}">`;

export function consentPage(input: { clientName: string; scopes: string; values: Record<string, string> }): string {
  const scopeLabels: Record<string, string> = { "analytics:read": "Analitikani ko'rish", "students:read": "Talabalar ma'lumotini ko'rish", "students:read:pii": "Talabalar PII ko'rish", "sales:read": "Savdo va to'lovlarni ko'rish", "chat:read": "Suhbatlarni ko'rish", "chat:write": "Suhbatga javob yozish", "content:write": "Sayt kontentini yangilash" };
  const labels = input.scopes.split(/\s+/).filter(Boolean).map((scope) => `<li>${esc(scopeLabels[scope] ?? scope)}</li>`).join("");
  const hidden = Object.entries(input.values).map(([name, value]) => field(name, value)).join("");
  return `<!doctype html><html lang="uz"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Naqsh MCP ulanishi</title><style>body{margin:0;background:#FAF7F0;color:#0E1A2B;font:17px/1.6 system-ui}.card{max-width:620px;margin:8vh auto;padding:32px;background:#fff;border:1px solid #E4DDCF;border-radius:20px;box-shadow:0 18px 60px #0e1a2b18}h1{line-height:1.2}ul{padding-left:24px}.actions{display:flex;gap:12px;margin-top:28px;flex-wrap:wrap}button{min-height:48px;padding:0 20px;border:0;border-radius:12px;font:inherit;font-weight:700;cursor:pointer}.allow{background:#E8A317;color:#0E1A2B}.cancel{background:#F1ECE1;color:#0E1A2B}@media(prefers-color-scheme:dark){body{background:#07111F;color:#EEF2F8}.card{background:#0E1B2E;border-color:#1D2B42}.cancel{background:#1D2B42;color:#EEF2F8}}</style><main class="card"><p>NAQSH · XAVFSIZ ULANISH</p><h1>${esc(input.clientName)} Naqsh ma'lumotlariga ulanmoqchi</h1><p>Faqat quyidagi ruxsatlarga kirish so'raladi. Ulanishni keyin admin sahifasidan uzishingiz mumkin.</p><ul>${labels}</ul><form method="post"><div>${hidden}<input type="hidden" name="decision" value="allow"></div><div class="actions"><button class="allow" type="submit">Ruxsat berish</button><a href="${esc(input.values.redirect_uri ?? "")}"><button class="cancel" type="button">Bekor qilish</button></a></div></form></main></html>`;
}
