"use client";

import { useEffect, useState } from "react";
import { Check, Copy, KeyRound, Link2, Loader2, ShieldCheck, Trash2 } from "lucide-react";
import { siteConfig } from "@/lib/siteConfig";
import { ALL_MCP_SCOPES, type McpScope } from "../contracts";

type Pat = { id: string; name: string; scopes: string[]; sender: string; expiresAt: string; lastUsedAt: string | null; revokedAt: string | null };
const labels: Record<string, string> = { "analytics:read": "Analitika", "students:read": "Talabalar", "sales:read": "Savdo", "chat:read": "Suhbatlar", "chat:write": "Suhbat yozish", "content:write": "Kontent", "students:read:pii": "Talaba PII" };

export function McpSettingsPanel() {
  const [items, setItems] = useState<Pat[]>([]); const [name, setName] = useState("Claude Code"); const [scopes, setScopes] = useState<McpScope[]>(["analytics:read", "students:read"]); const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const [managers, setManagers] = useState<{ id: string; name: string; email: string; mcpAccess: boolean }[] | null>(null);
  const endpoint = `${siteConfig.siteUrl}/api/mcp`;
  const load = () => {
    fetch("/api/v1/mcp/pats").then((response) => response.json()).then((body: { data?: Pat[] }) => setItems(body.data ?? [])).catch(() => setMessage("Tokenlar ro'yxatini yuklab bo'lmadi."));
    fetch("/api/v1/admin/mcp/managers").then((response) => response.ok ? response.json() : { data: null }).then((body) => setManagers(body.data)).catch(() => {});
  };
  useEffect(() => { void load(); }, []);
  async function create() { setLoading(true); const response = await fetch("/api/v1/mcp/pats", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, scopes, expiresInDays: 90, sender: "admin" }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setMessage(body.error?.message ?? "Token yaratilmadi"); return; } setToken(body.data.token); setMessage("Token yaratildi. Uni faqat bir marta ko'rsatamiz."); void load(); }
  async function revoke(id: string) { await fetch(`/api/v1/mcp/pats/${id}`, { method: "DELETE" }); void load(); }
  async function copy(value: string) { await navigator.clipboard.writeText(value); setMessage("Nusxalandi."); }
  async function toggleAccess(id: string, current: boolean) { await fetch(`/api/v1/admin/mcp/managers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mcpAccess: !current }) }); void load(); }
  return <section className="space-y-8">
    <div><h2 className="flex items-center gap-2 text-xl font-bold text-ink"><Link2 className="h-5 w-5 text-accent" />MCP ulanishlar</h2><p className="mt-2 max-w-2xl text-sm text-ink-muted">Claude, ChatGPT yoki Cursor'ga faqat kerakli ko'rsatkichlar va yozish ruxsatlarini bering. Tokenlar faqat bir marta ko'rsatiladi.</p></div>
    <div className="rounded-xl border border-brand/20 bg-brand-soft p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-brand" /><div><p className="font-semibold text-ink">Streamable HTTP endpoint</p><code className="mt-2 block overflow-x-auto rounded-lg bg-bg-elevated p-3 text-sm text-ink">{endpoint}</code><button type="button" onClick={() => void copy(endpoint)} className="mt-3 flex min-h-11 items-center gap-2 rounded-lg border border-border bg-bg-elevated px-4 text-sm font-semibold text-ink"><Copy className="h-4 w-4" />Endpointni nusxalash</button></div></div></div>
    {managers && managers.length > 0 && <div className="rounded-xl border border-border bg-bg-elevated p-5"><h3 className="font-semibold text-ink">Menejerlar uchun MCP ruxsati</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{managers.map(m => <div key={m.id} className="flex items-center justify-between rounded-lg border border-border p-3"><div><p className="font-medium text-ink">{m.name}</p><p className="text-xs text-ink-muted">{m.email}</p></div><label className="flex cursor-pointer items-center gap-2"><span className="text-sm font-medium text-ink">{m.mcpAccess ? "Yoniq" : "O'chiq"}</span><div className="relative inline-block h-6 w-11"><input type="checkbox" className="peer sr-only" checked={m.mcpAccess} onChange={() => void toggleAccess(m.id, m.mcpAccess)} /><div className="h-6 w-11 rounded-full bg-border transition-colors peer-checked:bg-success peer-focus-visible:ring-2 peer-focus-visible:ring-brand peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-bg"></div><div className="absolute left-[2px] top-[2px] h-5 w-5 rounded-full bg-white transition-transform peer-checked:translate-x-full"></div></div></label></div>)}</div></div>}
    <div className="grid gap-8 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-xl border border-border bg-bg-elevated p-5"><h3 className="font-semibold text-ink">Yangi personal access token</h3><label className="mt-4 block text-sm font-medium text-ink" htmlFor="pat-name">Token nomi</label><input id="pat-name" value={name} onChange={(event) => setName(event.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-bg px-3" /><fieldset className="mt-5"><legend className="text-sm font-medium text-ink">Ruxsatlar</legend><div className="mt-2 grid gap-2">{ALL_MCP_SCOPES.map((scope) => <label key={scope} className="flex min-h-11 items-center gap-3 rounded-lg border border-border px-3 text-sm"><input type="checkbox" checked={scopes.includes(scope)} onChange={() => setScopes((current) => current.includes(scope) ? current.filter((item) => item !== scope) : [...current, scope])} />{labels[scope] ?? scope}</label>)}</div></fieldset><button type="button" disabled={loading || !name || scopes.length === 0} onClick={() => void create()} className="mt-5 flex min-h-11 items-center gap-2 rounded-lg bg-gold px-4 font-semibold text-ink disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <KeyRound className="h-4 w-4" />}Token yaratish</button>{token && <div className="mt-4 rounded-lg border border-success/30 bg-success-soft p-3"><p className="text-sm font-semibold text-success">Token faqat shu yerda ko'rsatiladi</p><code className="mt-2 block break-all text-xs text-ink">{token}</code><button type="button" onClick={() => void copy(token)} className="mt-2 flex items-center gap-2 text-sm font-semibold text-brand"><Copy className="h-4 w-4" />Nusxalash</button></div>}</div>
      <div className="rounded-xl border border-border bg-bg-elevated p-5"><h3 className="font-semibold text-ink">Mavjud tokenlar</h3><div className="mt-4 space-y-3">{items.map((item) => <div key={item.id} className="rounded-lg border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-ink">{item.name}</p><p className="mt-1 text-xs text-ink-muted">{item.scopes.map((scope) => labels[scope] ?? scope).join(" · ")}</p></div>{item.revokedAt ? <span className="text-xs text-ink-subtle">Bekor qilingan</span> : <button type="button" aria-label={`${item.name} bekor qilish`} onClick={() => void revoke(item.id)} className="flex min-h-11 items-center gap-1 rounded-lg px-3 text-sm text-danger hover:bg-danger-soft"><Trash2 className="h-4 w-4" />Bekor qilish</button>}</div><p className="mt-3 text-xs text-ink-muted">Muddati: {new Date(item.expiresAt).toLocaleDateString("uz-UZ")} · Oxirgi foydalanish: {item.lastUsedAt ? new Date(item.lastUsedAt).toLocaleString("uz-UZ") : "hali yo'q"}</p></div>)}{items.length === 0 && <p className="text-sm text-ink-muted">Hali token yaratilmagan.</p>}</div></div></div>
    {message && <p role="status" className="flex items-center gap-2 text-sm font-medium text-brand"><Check className="h-4 w-4" />{message}</p>}
  </section>;
}
