"use client";
import { useCallback, useEffect, useState } from "react";
import type { CriterionResult, HomeworkStatus, HomeworkSubmission, ReviewDraft } from "./types";
import { DEFAULT_RUBRIC } from "./types";
export function useHomeworkQueue() { const [submissions, setSubmissions] = useState<HomeworkSubmission[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<HomeworkSubmission | null>(null); const [statusFilter, setStatusFilter] = useState<HomeworkStatus>("submitted"); const [criteria, setCriteria] = useState<CriterionResult[]>(DEFAULT_RUBRIC); const [feedbackMd, setFeedbackMd] = useState(""); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null);
 const fetchSubmissions = useCallback(async () => { setLoading(true); try { const res = await fetch(`/api/admin/homework?status=${statusFilter}`); if (!res.ok) throw new Error("Topshiriqlarni yuklab bo'lmadi"); const data: unknown = await res.json(); if (typeof data === "object" && data && "submissions" in data && Array.isArray(data.submissions)) setSubmissions(data.submissions as HomeworkSubmission[]); } catch (e) { console.error("fetchSubmissions error:", e); } finally { setLoading(false); } }, [statusFilter]); useEffect(() => { void fetchSubmissions(); }, [fetchSubmissions]);
 const open = (sub: HomeworkSubmission) => { setSelected(sub); setCriteria(sub.review?.criteriaResults || DEFAULT_RUBRIC); setFeedbackMd(sub.review?.feedbackMd || ""); setError(null); }; const grade = async (status: "approved" | "rejected") => { if (!selected) return; setSubmitting(true); setError(null); try { const total = criteria.reduce((s, c) => s + c.score, 0); const max = criteria.reduce((s, c) => s + c.maxScore, 0); const score = max ? Math.round((total / max) * 10 * 10) / 10 : 0; const res = await fetch(`/api/admin/homework/${selected.id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ submissionId: selected.id, criteriaResults: criteria, score, feedbackMd, status }) }); if (!res.ok) throw new Error("Baholashda xatolik yuz berdi"); setSelected(null); await fetchSubmissions(); } catch (e) { setError(e instanceof Error ? e.message : "Xatolik yuz berdi"); } finally { setSubmitting(false); } };
 return { submissions, loading, selected, setSelected, statusFilter, setStatusFilter, criteria, setCriteria, feedbackMd, setFeedbackMd, submitting, error, fetchSubmissions, open, grade };
}
export const scoreOf = (criteria: CriterionResult[]) => { const total = criteria.reduce((s, c) => s + c.score, 0); const max = criteria.reduce((s, c) => s + c.maxScore, 0); return max ? Math.round((total / max) * 10 * 10) / 10 : 0; };
