"use client";
import { useCallback, useEffect, useState } from "react";
import type { BroadcastItem, Cohort, NotificationAudience, NotificationChannel, NotificationStatus } from "./types";
export function useNotifications() { const [broadcasts, setBroadcasts] = useState<BroadcastItem[]>([]); const [cohorts, setCohorts] = useState<Cohort[]>([]); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  const fetchBroadcasts = useCallback(async () => { setLoading(true); try { const res = await fetch("/api/admin/notifications"); const data: unknown = await res.json(); if (typeof data === "object" && data && "success" in data && data.success && "broadcasts" in data && Array.isArray(data.broadcasts)) setBroadcasts(data.broadcasts as BroadcastItem[]); } catch (e) { console.error("Fetch broadcasts error:", e); } finally { setLoading(false); } }, []);
  useEffect(() => { void fetchBroadcasts(); void fetch("/api/admin/cohorts").then(r => r.json()).then((d: unknown) => { if (typeof d === "object" && d && "cohorts" in d && Array.isArray(d.cohorts)) setCohorts(d.cohorts as Cohort[]); }).catch(console.error); }, [fetchBroadcasts]);
  const send = async (title: string, channel: NotificationChannel, targetAudience: NotificationAudience, cohortId: string, messageBody: string, status: "sent" | "draft") => { if (!title.trim()) { alert("Xabarnoma nomini kiriting"); return; } if (!messageBody.trim()) { alert("Xabar matnini kiriting"); return; } setSending(true); try { const res = await fetch("/api/admin/notifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, channel, targetAudience, cohortId: targetAudience === "cohort_students" ? cohortId || null : null, messageBody, status }) }); const data: unknown = await res.json(); if (typeof data === "object" && data && "success" in data && data.success) { await fetchBroadcasts(); alert(status === "sent" ? "Xabarnoma muvaffaqiyatli yuborildi!" : "Qoralama saqlandi!"); } else alert("Xabarnoma yuborishda xatolik"); } catch (e) { console.error("Send broadcast error:", e); alert("Xabarnoma yuborishda xatolik yuz berdi"); } finally { setSending(false); } };
  return { broadcasts, cohorts, loading, sending, send };
}
