"use client";
import { FileText, Globe, Loader2, X } from "lucide-react";
import { MarkdownEditor } from "./MarkdownEditor";
import type { BlogForm, BlogPost, BlogStatus, EditorTab } from "./types";
interface Props { form: BlogForm; setForm: React.Dispatch<React.SetStateAction<BlogForm>>; editing: BlogPost | null; onClose: () => void; onSave: (e: React.FormEvent) => void; saving: boolean; tab: EditorTab; setTab: (t: EditorTab) => void; insert: (p: string, s?: string, d?: string) => void; }
const input = "w-full min-h-11 px-3.5 py-2 text-base bg-bg-elevated border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-accent";
export function BlogFormModal({ form, setForm, editing, onClose, onSave, saving, tab, setTab, insert }: Props) {
  const set = <K extends keyof BlogForm>(key: K, value: BlogForm[K]) => setForm(prev => ({ ...prev, [key]: value }));
  return <div className="fixed inset-0 z-50 flex items-end justify-center overflow-y-auto bg-ink/60 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="blog-form-title" className="my-0 flex max-h-[100dvh] w-full max-w-4xl flex-col overflow-hidden rounded-t-2xl bg-bg-sunken shadow-xl sm:my-8 sm:max-h-[calc(100dvh-2rem)] sm:rounded-2xl">
    <div className="flex items-center justify-between border-b border-border p-5"><div className="flex min-w-0 items-center gap-2"><FileText className="w-5 h-5 shrink-0 text-accent" aria-hidden="true" /><h2 id="blog-form-title" className="break-words text-lg font-bold text-ink">{editing ? "Maqolani Tahrirlash" : "Yangi Maqola Yaratish"}</h2></div><button type="button" onClick={onClose} aria-label="Maqola formasini yopish" className="grid min-h-11 min-w-11 place-items-center rounded-lg text-ink-muted hover:bg-bg-elevated hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"><X className="w-5 h-5" aria-hidden="true" /></button></div>
    <form onSubmit={onSave} className="min-h-0 flex-1 space-y-6 overflow-y-auto overscroll-contain p-6">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2"><div className="md:col-span-2"><label htmlFor="blog-title" className="mb-1 block text-xs font-medium text-ink">Maqola Sarlavhasi *</label><input id="blog-title" name="title" autoComplete="off" type="text" required placeholder="Masalan: Vibe Coding bilan 2 soatda AI bot yaratish" value={form.title} onChange={e => set("title", e.target.value)} className={input} /></div><div><label htmlFor="blog-slug" className="mb-1 block text-xs font-medium text-ink">URL Slug *</label><input id="blog-slug" name="slug" type="text" required placeholder="vibe-coding-ai-bot" value={form.slug} onChange={e => set("slug", e.target.value)} className={`${input} font-mono`} /></div><div><label htmlFor="blog-category" className="mb-1 block text-xs font-medium text-ink">Kategoriya *</label><input id="blog-category" name="category" type="text" required placeholder="Vibe Coding, AI Vositalar..." value={form.category} onChange={e => set("category", e.target.value)} className={input} /></div><div><label htmlFor="blog-author" className="mb-1 block text-xs font-medium text-ink">Muallif Ismi</label><input id="blog-author" name="authorName" autoComplete="name" type="text" value={form.authorName} onChange={e => set("authorName", e.target.value)} className={input} /></div><div><label htmlFor="blog-cover" className="mb-1 block text-xs font-medium text-ink">Rasm (Cover URL)</label><input id="blog-cover" name="coverUrl" type="url" placeholder="https://images.unsplash.com/..." value={form.coverUrl} onChange={e => set("coverUrl", e.target.value)} className={input} /></div></div>
      <div><label htmlFor="blog-excerpt" className="mb-1 block text-xs font-medium text-ink">Qisqacha Tavsif (Excerpt)</label><textarea id="blog-excerpt" name="excerpt" rows={2} placeholder="Maqola kartochkasida va qidiruv natijalarida ko'rinadigan qisqa mazmun..." value={form.excerpt} onChange={e => set("excerpt", e.target.value)} className={`${input} min-h-16`} /></div>
      <MarkdownEditor tab={tab} setTab={setTab} contentMd={form.contentMd} setContentMd={v => set("contentMd", v)} insert={insert} />
      <div className="space-y-3 rounded-xl border border-border bg-bg-elevated/50 p-4"><div className="flex items-center gap-2"><Globe className="w-4 h-4 text-accent" aria-hidden="true" /><h3 className="text-xs font-bold uppercase text-ink tracking-wider">SEO va Metama'lumotlar</h3></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2"><label className="sr-only" htmlFor="blog-seo-title">SEO Sarlavha</label><input id="blog-seo-title" aria-label="SEO Sarlavha (Title Tag)" placeholder="Google qidiruvidagi sarlavha (max 60 ta belgi)" value={form.seoTitle} onChange={e => set("seoTitle", e.target.value)} className="min-h-11 w-full rounded-lg border border-border bg-bg-elevated px-3 py-2 text-base focus:outline-none focus:ring-2 focus:ring-accent" /><label className="sr-only" htmlFor="blog-seo-description">SEO Tavsif</label><input id="blog-seo-description" aria-label="SEO Tavsif (Meta Description)" placeholder="Google qidiruvidagi tavsif (max 160 ta belgi)" value={form.seoDescription} onChange={e => set("seoDescription", e.target.value)} className="min-h-11 w-full rounded-lg border border-border bg-bg-elevated px-3 py-2 text-base focus:outline-none focus:ring-2 focus:ring-accent" /></div></div>
      <div className="grid grid-cols-1 gap-4 border-t border-border pt-4 md:grid-cols-2"><div><label htmlFor="blog-status" className="mb-1 block text-xs font-medium text-ink">Chop etish holati *</label><select id="blog-status" name="status" value={form.status} onChange={e => set("status", e.target.value as BlogStatus)} className={`${input} appearance-none`}><option value="published">Chop etilgan (Published)</option><option value="scheduled">Rejalashtirilgan (Scheduled)</option><option value="draft">Qoralama (Draft)</option><option value="archived">Arxivlangan (Archived)</option></select></div><div><label htmlFor="blog-published-at" className="mb-1 block text-xs font-medium text-ink">Chop etish vaqti (Publish Date)</label><input id="blog-published-at" name="publishedAt" type="datetime-local" value={form.publishedAt} onChange={e => set("publishedAt", e.target.value)} className={input} /></div></div>
      <div className="flex flex-col items-stretch justify-end gap-3 border-t border-border pt-4 sm:flex-row"><button type="button" onClick={onClose} className="min-h-11 rounded-lg px-4 py-2 text-sm font-medium text-ink-muted hover:text-ink">Bekor qilish</button><button type="submit" disabled={saving} className="inline-flex min-h-11 items-center justify-center rounded-lg bg-accent px-5 py-2 text-sm font-medium text-ink shadow-sm hover:bg-accent/90 disabled:opacity-50">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" /> : null}{saving ? "Saqlanmoqda…" : editing ? "O'zgarishlarni Saqlash" : "Maqolani Yaratish"}</button></div>
    </form>
  </div></div>;
}
