"use client";
import { FileText, Globe, Loader2, X } from "lucide-react";
import { MarkdownEditor } from "./MarkdownEditor";
import type { BlogForm, BlogPost, BlogStatus, EditorTab } from "./types";
interface Props { form: BlogForm; setForm: React.Dispatch<React.SetStateAction<BlogForm>>; editing: BlogPost | null; onClose: () => void; onSave: (e: React.FormEvent) => void; saving: boolean; tab: EditorTab; setTab: (t: EditorTab) => void; insert: (p: string, s?: string, d?: string) => void; }
const input = "w-full px-3.5 py-2 text-sm bg-bg-elevated border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-accent";
export function BlogFormModal({ form, setForm, editing, onClose, onSave, saving, tab, setTab, insert }: Props) {
  const set = <K extends keyof BlogForm>(key: K, value: BlogForm[K]) => setForm(prev => ({ ...prev, [key]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ink/60 backdrop-blur-sm overflow-y-auto"><div className="bg-bg-sunken border border-border rounded-2xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-xl my-8"><div className="flex items-center justify-between p-5 border-b border-border"><div className="flex items-center gap-2"><FileText className="w-5 h-5 text-accent" /><h2 className="text-lg font-bold text-ink">{editing ? "Maqolani Tahrirlash" : "Yangi Maqola Yaratish"}</h2></div><button onClick={onClose} className="p-1.5 rounded-lg text-ink-muted hover:text-ink hover:bg-bg-elevated transition-colors"><X className="w-5 h-5" /></button></div><form onSubmit={onSave} className="flex-1 overflow-y-auto p-6 space-y-6">
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2"><label className="block text-xs font-medium text-ink mb-1">Maqola Sarlavhasi *</label><input type="text" required placeholder="Masalan: Vibe Coding bilan 2 soatda AI bot yaratish" value={form.title} onChange={e => set("title", e.target.value)} className={input} /></div><div><label className="block text-xs font-medium text-ink mb-1">URL Slug *</label><input type="text" required placeholder="vibe-coding-ai-bot" value={form.slug} onChange={e => set("slug", e.target.value)} className={`${input} font-mono`} /></div><div><label className="block text-xs font-medium text-ink mb-1">Kategoriya *</label><input type="text" required placeholder="Vibe Coding, AI Vositalar..." value={form.category} onChange={e => set("category", e.target.value)} className={input} /></div><div><label className="block text-xs font-medium text-ink mb-1">Muallif Ismi</label><input type="text" value={form.authorName} onChange={e => set("authorName", e.target.value)} className={input} /></div><div><label className="block text-xs font-medium text-ink mb-1">Rasm (Cover URL)</label><input type="url" placeholder="https://images.unsplash.com/..." value={form.coverUrl} onChange={e => set("coverUrl", e.target.value)} className={input} /></div></div>
    <div><label className="block text-xs font-medium text-ink mb-1">Qisqacha Tavsif (Excerpt)</label><textarea rows={2} placeholder="Maqola kartochkasida va qidiruv natijalarida ko'rinadigan qisqa mazmun..." value={form.excerpt} onChange={e => set("excerpt", e.target.value)} className={input} /></div>
    <MarkdownEditor tab={tab} setTab={setTab} contentMd={form.contentMd} setContentMd={v => set("contentMd", v)} insert={insert} />
    <div className="border border-border rounded-xl p-4 bg-bg-elevated/50 space-y-3"><div className="flex items-center gap-2"><Globe className="w-4 h-4 text-accent" /><h3 className="text-xs font-bold uppercase text-ink tracking-wider">SEO va Metama'lumotlar</h3></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><input aria-label="SEO Sarlavha (Title Tag)" placeholder="Google qidiruvidagi sarlavha (max 60 ta belgi)" value={form.seoTitle} onChange={e => set("seoTitle", e.target.value)} className="w-full px-3 py-2 text-xs bg-bg-elevated border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-accent" /><input aria-label="SEO Tavsif (Meta Description)" placeholder="Google qidiruvidagi tavsif (max 160 ta belgi)" value={form.seoDescription} onChange={e => set("seoDescription", e.target.value)} className="w-full px-3 py-2 text-xs bg-bg-elevated border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-accent" /></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-border pt-4"><div><label className="block text-xs font-medium text-ink mb-1">Chop etish holati *</label><select value={form.status} onChange={e => set("status", e.target.value as BlogStatus)} className="w-full px-3.5 py-2 text-sm bg-bg-elevated border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-accent"><option value="published">Chop etilgan (Published)</option><option value="scheduled">Rejalashtirilgan (Scheduled)</option><option value="draft">Qoralama (Draft)</option><option value="archived">Arxivlangan (Archived)</option></select></div><div><label className="block text-xs font-medium text-ink mb-1">Chop etish vaqti (Publish Date)</label><input type="datetime-local" value={form.publishedAt} onChange={e => set("publishedAt", e.target.value)} className="w-full px-3.5 py-2 text-sm bg-bg-elevated border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-accent" /></div></div>
    <div className="flex items-center justify-end gap-3 pt-4 border-t border-border"><button type="button" onClick={onClose} className="px-4 py-2 text-sm font-medium text-ink-muted hover:text-ink transition-colors">Bekor qilish</button><button type="submit" disabled={saving} className="inline-flex items-center justify-center px-5 py-2 text-sm font-medium text-ink bg-accent rounded-lg hover:bg-accent/90 transition-colors shadow-sm disabled:opacity-50">{saving ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}{editing ? "O'zgarishlarni Saqlash" : "Maqolani Yaratish"}</button></div>
  </form></div></div>;
}
