"use client";
import { useCallback, useEffect, useState } from "react";
import type { BlogForm, BlogPost, BlogStatusFilter } from "./types";
export function useBlogs() {
  const [posts, setPosts] = useState<BlogPost[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState<BlogStatusFilter>("all"); const [saving, setSaving] = useState(false);
  const fetchPosts = useCallback(async () => { setLoading(true); try { const p = new URLSearchParams(); if (search) p.append("search", search); if (statusFilter !== "all") p.append("status", statusFilter); const res = await fetch(`/api/admin/blog?${p}`); const data: unknown = await res.json(); if (typeof data === "object" && data && "success" in data && data.success && "posts" in data && Array.isArray(data.posts)) setPosts(data.posts as BlogPost[]); } catch (e) { console.error("Failed to fetch blog posts:", e); } finally { setLoading(false); } }, [search, statusFilter]);
  useEffect(() => { void fetchPosts(); }, [fetchPosts]);
  const save = async (form: BlogForm, editing: BlogPost | null) => { setSaving(true); try { const res = await fetch(editing ? `/api/admin/blog/${editing.id}` : "/api/admin/blog", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.title, slug: form.slug, category: form.category, authorName: form.authorName, coverUrl: form.coverUrl || null, excerpt: form.excerpt || null, contentMd: form.contentMd, seoTitle: form.seoTitle || null, seoDescription: form.seoDescription || null, status: form.status, publishedAt: form.publishedAt ? new Date(form.publishedAt).toISOString() : new Date().toISOString() }) }); const data: unknown = await res.json(); if (typeof data === "object" && data && "success" in data && data.success) { await fetchPosts(); return true; } alert(typeof data === "object" && data && "error" in data && typeof data.error === "string" ? data.error : "Xatolik yuz berdi"); } catch (e) { console.error("Save error:", e); alert("Saqlashda xatolik yuz berdi"); } finally { setSaving(false); } return false; };
  const remove = async (id: string) => { if (!confirm("Haqiqatan ham ushbu maqolani o'chirmoqchimisiz?")) return; try { const res = await fetch(`/api/admin/blog/${id}`, { method: "DELETE" }); const data: unknown = await res.json(); if (typeof data === "object" && data && "success" in data && data.success) await fetchPosts(); else alert("O'chirishda xatolik"); } catch (e) { console.error("Delete error:", e); } };
  return { posts, loading, search, setSearch, statusFilter, setStatusFilter, saving, save, remove };
}
